#!/bin/bash
# 分析scripts文件夹中的脚本用途
# 判断哪些是必需的，哪些是冗余的

PROJECT_ROOT="/home/long/energy_baseline_training/projects/shiyan7"

echo "================================================================================"
echo "                    scripts文件夹脚本分析"
echo "================================================================================"

echo ""
echo "[1] 脚本文件列表"

echo ""
echo "文件名                                    大小    用途"
echo "----------------------------------------------------------------------------------------"

ls -lh "$PROJECT_ROOT/scripts/" | grep -v "^d" | grep -v "^total" | while read -r perms links user group size month day time name; do
    echo "$name    $size"
done

echo ""
echo "[2] 脚本详细分析"

echo ""
echo "========================================================================="
echo "必需脚本 (需要更新并保留) ⭐"
echo "========================================================================="
echo ""
echo "1. predict_advanced.py (11K) ⭐"
echo "   当前状态: 加载v2.0模型 (best_model_advanced.pkl)"
echo "   问题: 使用12个特征，含month和delta_temp_header"
echo "   建议: 需要更新为v3.0模型"
echo "   用途: 核心预测脚本，用于生产环境"
echo ""
echo "2. train_final_model.py (8.8K) ⭐"
echo "   当前状态: 可用"
echo "   用途: 训练v3.0模型"
echo "   状态: 已完成训练"
echo ""

echo "========================================================================="
echo "一次性脚本 (已完成，可保留或归档)"
echo "========================================================================="
echo ""
echo "3. evaluate_december_accuracy.py (11K) - 12月精度评估"
echo "   用途: 评估12月预测精度"
echo "   状态: 已完成，生成报告"
echo "   建议: 保留 (可复用）"
echo ""
echo "4. predict_december_only.py (5.6K) - 12月预测"
echo "   用途: 预测12月能耗"
echo "   状态: 已完成"
echo "   建议: 保留 (可复用）"
echo ""
echo "5. compare_december_accuracy.py (8.7K) - v3.0 vs v3.1对比"
echo "   用途: 对比两个版本的12月预测精度"
echo "   状态: 已完成"
echo "   建议: 保留 (分析结论已记录)"
echo ""

echo "========================================================================="
echo "旧版本脚本 (可归档)"
echo "========================================================================="
echo ""
echo "6. retrain_model.py (11K) - v2.0训练脚本"
echo "   用途: 训练v2.0模型"
echo "   状态: 已被train_final_model.py替代"
echo "   建议: 归档或删除"
echo ""
echo "7. predict_december.py (8.5K) - 初始12月预测脚本"
echo "   用途: 初始12月预测脚本"
echo "   状态: 已被predict_december_only.py替代"
echo "   建议: 归档或删除"
echo ""
echo "8. predict_december_v31.py (6.1K) - v3.1版本预测"
echo "   用途: 12月v3.1模型预测"
echo "   状态: v3.1不推荐使用"
echo "   建议: 归档或删除"
echo ""
echo "9. analyze_year_round_prediction.py (11K) - 全年预测分析"
echo "   用途: 分析month特征问题"
echo "   状态: 已完成分析"
echo "   建议: 归档或删除 (问题已解决)"
echo ""
echo "10. train_with_transition.py (9.6K) - v3.1训练脚本"
echo "    用途: 训练v3.1模型（含加减机标记）"
echo "    状态: 已完成，但不推荐"
echo "    建议: 归档或删除 (存在过拟合)"
echo ""

echo "========================================================================="
echo "临时脚本"
echo "========================================================================="
echo ""
echo "11. cleanup_project.sh (4.3K) - 项目清理脚本"
echo "    用途: 清理中间文件"
echo "    状态: 已执行"
echo "    建议: 保留 (未来可复用)"
echo ""

echo ""
echo "[3] 推荐操作"

echo ""
echo "选项A: 最小化 (仅保留必需)"
echo "================================"
echo ""
echo "保留:"
echo "  ✓ predict_advanced.py (需要更新为v3.0)"
echo "  ✓ train_final_model.py"
echo "  ✓ predict_december_only.py"
echo "  ✓ evaluate_december_accuracy.py"
echo "  ✓ cleanup_project.sh"
echo ""
echo "删除/归档:"
echo "  ✓ retrain_model.py"
echo "  ✓ predict_december.py"
echo "  ✓ predict_december_v31.py"
echo "  ✓ compare_december_accuracy.py"
echo "  ✓ analyze_year_round_prediction.py"
echo "  ✓ train_with_transition.py"
echo ""
echo "删除后: 11个文件 → 5个文件"
echo ""

echo ""
echo "选项B: 保守 (保留所有，分类管理)"
echo "================================"
echo ""
echo "创建子文件夹:"
echo "  scripts/active/ (活跃脚本)"
echo "    - predict_advanced.py"
echo "    - train_final_model.py"
echo "    - predict_december_only.py"
echo "    - evaluate_december_accuracy.py"
echo ""
echo "  scripts/archive/ (归档脚本)"
echo "    - retrain_model.py"
echo "    - train_with_transition.py"
echo "    - predict_december.py"
echo "    - predict_december_v31.py"
echo "    - compare_december_accuracy.py"
echo "    - analyze_year_round_prediction.py"
echo ""
echo "  scripts/util/ (工具脚本)"
echo "    - cleanup_project.sh"
echo ""

echo ""
echo "[4] 立即行动建议"
echo ""
echo "1. 更新predict_advanced.py:"
echo "   - 修改模型文件: best_model_advanced.pkl → best_model_final.pkl"
echo "   - 修改特征列表: advanced_feature_columns.pkl → final_feature_columns.pkl"
echo "   - 修改特征数量: 12 → 10"
echo "   - 移除delta_temp_header参数"
echo "   - 更新MAPE显示: 2.08% → 2.55%"
echo ""
echo "2. 整理脚本文件夹:"
echo "   - 选项A: 删除旧版本脚本 (推荐)"
echo "   - 选项B: 分类管理脚本"
echo ""

echo ""
echo "[5] 脚本用途总结"
echo ""
echo "生产使用 (必需):"
echo "  • predict_advanced.py - 核心预测接口"
echo "  • train_final_model.py - 模型训练"
echo ""
echo "数据分析 (已完成):"
echo "  • evaluate_december_accuracy.py - 12月精度评估"
echo "  • predict_december_only.py - 12月预测"
echo "  • compare_december_accuracy.py - 版本对比"
echo "  • analyze_year_round_prediction.py - 全年分析"
echo ""
echo "实验/废弃:"
echo "  • retrain_model.py - 旧版训练"
echo "  • train_with_transition.py - 实验版本"
echo "  • predict_december.py - 旧版预测"
echo "  • predict_december_v31.py - 实验版本"
echo ""

echo "================================================================================"
echo "分析完成"
echo "================================================================================"
